In [ ]:
from datasets import load_dataset
import pandas as pd

ds = load_dataset("textdetox/multilingual_toxicity_dataset")
Data2 : str = "/home/s2shsinh/data/processed/DefaktS_Twitter.binary.csv"


dataset= ds['de'].to_pandas()
dataset.to_csv("multilingual_toxicity.csv", index=False)
print(dataset.head())

                                                text  toxic
0   Untaten mit "Flüchtlingen" oder Moslems in Ve...      0
1  Der Regenwald wird im Akkord abgeholzt ,das in...      0
2      Es geht darum was der Makler sich rein zieht.      0
3   Huhhhhh, Fritz, Du jagst mir richtig Angst ein 😜      0
4     Hab versucht zu entziffern was du da von di...      1

In [21]:
# Load the dataset
import pandas as pd
file_name = "/home/s2shsinh/TWON_Metrics/dataset/DefaktS_Twitter.binary.csv"  # Replace with your dataset file name
df = pd.read_csv(file_name)

# Separate the dataset into two groups based on the label
label_0 = df[df['binary_label'] == 0]
label_1 = df[df['binary_label'] == 1]

# Randomly sample 2500 records from each group
sample_0 = label_0.sample(n=2500, random_state=42)
sample_1 = label_1.sample(n=2500, random_state=42)

# Combine the samples into a new dataset
balanced_sample = pd.concat([sample_0, sample_1])

# Shuffle the combined dataset
balanced_sample = balanced_sample.sample(frac=1, random_state=42).reset_index(drop=True)

# Save the balanced dataset to a new CSV file
balanced_sample.to_csv("balanced_dataset.csv", index=False)

print("Balanced dataset saved as 'balanced_dataset.csv'.")

Balanced dataset saved as 'balanced_dataset.csv'.

In [20]:
data3 ='/home/s2shsinh/TWON_Metrics/dataset/gahd.csv'
input_file = "your_dataset.csv"  # Replace with your CSV file name
output_file = "gahd_filtered.csv"  # Name of the new CSV file
import pandas as pd
# Read the CSV file into a DataFrame
df = pd.read_csv(data3)

# Filter only the 'text' and 'label' columns
filtered_df = df[['text', 'label']]

# Save the filtered DataFrame to a new CSV file
filtered_df.to_csv(output_file, index=False)

print(f"Filtered dataset saved as '{output_file}'.")

Filtered dataset saved as 'gahd_filtered.csv'.

#converting into single db

In [23]:
import pandas as pd

# Load the three datasets
fake_news = pd.read_csv("/home/s2shsinh/TWON_Metrics/dataset/balanced_dataset.csv")  # Replace with the actual file name
hate_speech = pd.read_csv("/home/s2shsinh/TWON_Metrics/dataset/gahd_filtered.csv")
toxicity = pd.read_csv("/home/s2shsinh/TWON_Metrics/dataset/multilingual_toxicity.csv")

# Add a unique label column for each dataset
# Add unique label columns based on their respective labels
fake_news['fake'] = fake_news['binary_label'].apply(lambda x: 1 if x == 1 else 0)
fake_news['hatespeech'] = 0
fake_news['toxicity'] = 0

hate_speech['fake'] = 0
hate_speech['hatespeech'] = hate_speech['label'].apply(lambda x: 1 if x == 1 else 0)
hate_speech['toxicity'] = 0

toxicity['fake'] = 0
toxicity['hatespeech'] = 0
toxicity['toxicity'] = toxicity['toxic'].apply(lambda x: 1 if x == 1 else 0)

# Ensure all datasets have the same columns
fake_news = fake_news[['text', 'fake', 'hatespeech', 'toxicity']]
hate_speech = hate_speech[['text', 'fake', 'hatespeech', 'toxicity']]
toxicity = toxicity[['text', 'fake', 'hatespeech', 'toxicity']]

# Combine the datasets
combined_dataset = pd.concat([fake_news, hate_speech, toxicity], ignore_index=True)

# Save the combined dataset to a new CSV file
combined_dataset.to_csv("combined_dataset1.csv", index=False)

print("Combined dataset saved as 'combined_dataset1.csv'.")

Combined dataset saved as 'combined_dataset1.csv'.

In [3]:
import pandas as pd
combo = pd.read_csv("/home/s2shsinh/TWON_Metrics/combined_dataset1.csv")

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 711, in start
    self.io_loop.start()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 729, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 411, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 531, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3006, in run_cell
    result = self._run_cell(
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3061, in _run_cell
    result = runner(coro)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3266, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3445, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_867842/2304129656.py", line 1, in <module>
    import pandas as pd
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 711, in start
    self.io_loop.start()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 729, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 411, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 531, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3006, in run_cell
    result = self._run_cell(
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3061, in _run_cell
    result = runner(coro)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3266, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3445, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_867842/2304129656.py", line 1, in <module>
    import pandas as pd
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/arrays/masked.py", line 60, in <module>
    from pandas.core import (
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/home/s2shsinh/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/anaconda/envs/transformers4.29.0/lib/python3.10/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

len(combo)

In [ ]:
combo.head()

,text,fake,hatespeech,toxicity
0,Im Studio von @1730Sat1live sprechen wir heute...,0,0,0
1,Die Frauen &amp; Männer im #Iran haben einen W...,1,0,0
2,Politiker*innen samt #LinksgrüneMedien und #ÖR...,1,0,0
3,gigi hat einfach überhaupt keine lust mehr auf...,0,0,0
4,In Österreich 🇦🇹 ist Bundespräsident @vanderb...,0,0,0

In [5]:
shuffled_df = combo.sample(frac=1, random_state=43)  # `frac=1` shuffles all rows

# Display the first few rows of the shuffled dataset
randomized_head = shuffled_df.head()
randomized_head

,text,fake,hatespeech,toxicity
3297,Erdbeben in der Türkei und Syrien: Nun mindest...,0,0,0
10304,"Wenn jemand denkt, das Judentum sei etwas Sinn...",0,1,0
4655,Heute bei „6 vor 9“: https://t.co/kNmkfjIKrR\n...,0,0,0
12021,Burka-Frauen sollten auf dem Scheiterhaufen ve...,0,1,0
15830,Letzte Nacht sah ich einige Japaner auf meinem...,0,1,0